# generated by Grok3

import pyxel
from TennisEngine import *

class App:
    W = 0
    S = 1
    D = 2
    Up = 3
    Down = 4
    Left = 5

    def __init__(self):
        # 画面サイズをサイズ (256, 256) に合わせる
        pyxel.init(256,256)
        # TennisEngine を初期化（バッファサイズとして 256x256 を指定）
        self.my_engine = TennisEngine(256, 256)
        self.keys = [False] * 6  # W, S, D, Up, Down, Left
        # 画像の読み込み（frame.png と overlay.png が必要）
        #pyxel.images[0].load(0, 0, "frame.png")  # イメージバンク 0 に frame.png
        #pyxel.images[1].load(0, 0, "overlay.png")  # イメージバンク 1 に overlay.png
        # キーイベントを登録
        pyxel.run(self.update, self.draw)

    def update(self):
        # キー入力の処理
        self.keys[self.W] = pyxel.btn(pyxel.KEY_W)
        self.keys[self.S] = pyxel.btn(pyxel.KEY_S)
        self.keys[self.D] = pyxel.btn(pyxel.KEY_D)
        self.keys[self.Up] = pyxel.btn(pyxel.KEY_UP)
        self.keys[self.Down] = pyxel.btn(pyxel.KEY_DOWN)
        self.keys[self.Left] = pyxel.btn(pyxel.KEY_LEFT)

        # スペースキーでヒット
        if pyxel.btnp(pyxel.KEY_SPACE):
            self.my_engine.hit()

        # 'i' キーでスクリーンショット保存
        if pyxel.btnp(pyxel.KEY_I):
            pyxel.save("pic{:03d}.png".format(pyxel.frame_count))

        # ゲームエンジンの更新
        self.my_engine.update(self.keys)

    def draw(self):
        # 背景をクリア（黒）
        pyxel.cls(0)
        # ゲームエンジンの描画
        self.my_engine.draw()
        # バッファを画面に描画（0, 0 のオフセットで 256x256 の領域）
        pyxel.blt(0, 0, 0, 0, 0, 256, 256, colkey=0)
        # フレーム画像の描画
        pyxel.blt(0, 0, 0, 0, 0, 256, 256, colkey=0)
        # オーバーレイ画像の描画（ADD ブレンドを模倣）
        pyxel.blt(0, 0, 1, 0, 0, 256, 256, colkey=0)

App()

# App.py
