# generated by Grok3

import pyxel

class Ball:
    def __init__(self, p_pos_x, p_pos_y):
        self.pos_x = self.prev_pos_x = p_pos_x
        self.pos_y = self.prev_pos_y = p_pos_y
        self.vel_x = 0
        self.vel_y = 0

    def update(self, p_gravity):
        self.prev_pos_x = self.pos_x
        self.prev_pos_y = self.pos_y
        self.vel_y += p_gravity
        self.pos_x += self.vel_x
        self.pos_y += self.vel_y

    def draw(self):
        # 線を描画
        pyxel.line(self.prev_pos_x, self.prev_pos_y, self.pos_x, self.pos_y, 14)
        # 点を描画
        pyxel.pset(self.pos_x, self.pos_y, 14)

    def bounce_floor(self, p_bounce):
        self.vel_y = -self.vel_y * p_bounce

    def bounce_fence(self, p_bounce):
        self.vel_x = -self.vel_x * p_bounce

    def set_speed(self, p_vel_x, p_vel_y):
        self.vel_x = p_vel_x
        self.vel_y = p_vel_y

    def set_position(self, p_pos_x, p_pos_y):
        self.pos_x = p_pos_x
        self.pos_y = p_pos_y

    def set_prev_position(self, p_pos_x, p_pos_y):
        self.prev_pos_x = p_pos_x
        self.prev_pos_y = p_pos_y

# End of Ball.py        
